PierresTreats/Models/Treat.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PierresTreats.Models
{
  public class Treat
  {
    public int TreatId { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }

    [DisplayFormat(DataFormatString = "{0:n2}", ApplyFormatInEditMode = true)]
    public decimal Price { get; set; }

    public virtual ICollection<FlavorTreat> FlavorTreatJoinEntities { get; }
    public virtual ApplicationUser User { get; set; }

    public Treat()
    {
      this.FlavorTreatJoinEntities = new HashSet<FlavorTreat>();
    }
  }
}

PierresTreats/Controllers/FlavorsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PierresTreats.Models;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace PierresTreats.Controllers
{
  [Authorize]
  public class FlavorsController : Controller
  {
    private readonly PierresTreatsContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public FlavorsController(PierresTreatsContext db, UserManager<ApplicationUser> userManager)
    {
      _db = db;
      _userManager = userManager;
    }

    [AllowAnonymous]
    public ActionResult Index()
    {
      List<Flavor> allFlavors = _db.Flavors.ToList();
      return View(allFlavors);
    }

    public ActionResult Create()
    {
      ViewBag.Treats = _db.Treats.ToList();
      return View();
    }

    [HttpPost]
    public ActionResult Create(Flavor flavor, int[] treatIds)
    {
      _db.Flavors.Add(flavor);
      _db.SaveChanges();
      foreach (int treatId in treatIds)
      {
        bool entryExists = _db.FlavorTreat
          .Any(entry => entry.FlavorId == flavor.FlavorId && entry.TreatId == treatId);
        if (!entryExists)
        {
          _db.FlavorTreat.Add(new FlavorTreat() { FlavorId = flavor.FlavorId, TreatId = treatId });
        }
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [AllowAnonymous]
    public ActionResult Details(int id)
    {
      Flavor selectedFlavor = _db.Flavors
        .Include(flavor => flavor.FlavorTreatJoinEntities)
        .ThenInclude(join => join.Treat)
        .FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(selectedFlavor);
    }

    public ActionResult Edit(int id)
    {
      Flavor selectedFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(selectedFlavor);
    }

    [HttpPost]
    public ActionResult Edit(Flavor flavor)
    {
      _db.Entry(flavor).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = flavor.FlavorId });
    }

    public ActionResult Delete(int id)
    {
      Flavor selectedFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(selectedFlavor);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Flavor selectedFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      _db.Flavors.Remove(selectedFlavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddTreat(int id)
    {
      Flavor selectedFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      ViewBag.Treats = _db.Treats.ToList();
      return View(selectedFlavor);
    }

    [HttpPost]
    public ActionResult AddTreat(Flavor flavor, int[] treatIds)
    {
      foreach (int treatId in treatIds)
      {
        bool entryExists = _db.FlavorTreat
          .Any(entry => entry.FlavorId == flavor.FlavorId && entry.TreatId == treatId);
        if (!entryExists)
        {
          _db.FlavorTreat.Add(new FlavorTreat() { FlavorId = flavor.FlavorId, TreatId = treatId });
        }
      }
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = flavor.FlavorId });
    }

    [HttpPost]
    public ActionResult RemoveTreat(int joinId)
    {
      FlavorTreat joinEntry = _db.FlavorTreat.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
      int flavorId = joinEntry.FlavorId;
      _db.FlavorTreat.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = flavorId });
    }
  }
}

PierresTreats/Controllers/TreatsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PierresTreats.Models;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace PierresTreats.Controllers
{
  [Authorize]
  public class TreatsController : Controller
  {
    private readonly PierresTreatsContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public TreatsController(PierresTreatsContext db, UserManager<ApplicationUser> userManager)
    {
      _db = db;
      _userManager = userManager;
    }

    [AllowAnonymous]
    public ActionResult Index()
    {
      List<Treat> allTreats = _db.Treats.ToList();
      return View(allTreats);
    }

    public ActionResult Create()
    {
      ViewBag.Flavors = _db.Flavors.ToList();
      return View();
    }

    [HttpPost]
    public ActionResult Create(Treat treat, int[] flavorIds)
    {
      _db.Treats.Add(treat);
      _db.SaveChanges();
      foreach (int flavorId in flavorIds)
      {
        bool entryExists = _db.FlavorTreat
          .Any(entry => entry.FlavorId == flavorId && entry.TreatId == treat.TreatId);
        if (!entryExists)
        {
          _db.FlavorTreat.Add(new FlavorTreat() { FlavorId = flavorId, TreatId = treat.TreatId });
        }
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [AllowAnonymous]
    public ActionResult Details(int id)
    {
      Treat selectedTreat = _db.Treats
        .Include(treat => treat.FlavorTreatJoinEntities)
        .ThenInclude(join => join.Flavor)
        .FirstOrDefault(treat => treat.TreatId == id);
      return View(selectedTreat);
    }

    public ActionResult Edit(int id)
    {
      Treat selectedTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(selectedTreat);
    }

    [HttpPost]
    public ActionResult Edit(Treat treat)
    {
      _db.Entry(treat).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = treat.TreatId });
    }

    public ActionResult Delete(int id)
    {
      Treat selectedTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(selectedTreat);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Treat selectedTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      _db.Treats.Remove(selectedTreat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddFlavor(int id)
    {
      Treat selectedTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      ViewBag.Flavors = _db.Flavors.ToList();
      return View(selectedTreat);
    }

    [HttpPost]
    public ActionResult AddFlavor(Treat treat, int[] flavorIds)
    {
      foreach (int flavorId in flavorIds)
      {
        bool entryExists = _db.FlavorTreat
          .Any(entry => entry.FlavorId == flavorId && entry.TreatId == treat.TreatId);
        if (!entryExists)
        {
          _db.FlavorTreat.Add(new FlavorTreat() { FlavorId = flavorId, TreatId = treat.TreatId });
        }
      }
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = treat.TreatId });
    }

    [HttpPost]
    public ActionResult RemoveFlavor(int joinId)
    {
      FlavorTreat joinEntry = _db.FlavorTreat.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
      int treatId = joinEntry.TreatId;
      _db.FlavorTreat.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = treatId });
    }
  }
}

PierresTreats/Views/Treats/AddFlavor.cshtml
@{
  Layout = "_Layout";
}

@using PierresTreats.Models
@model PierresTreats.Models.Treat

<h1>Add Flavors to @Html.DisplayFor(model => model.Name)</h1>

<div class="container page-content">
  <h4>Flavor Profile:</h4>
  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.TreatId)

    @if (@ViewBag.Flavors.Count == 0)
    {
      <p>No Flavor Selections Added</p>
    }
    else
    {
      <ul>
        @foreach (Flavor flavor in ViewBag.Flavors)
        {
          <li>
            <input type="checkbox" name="flavorIds" value="@flavor.FlavorId" />
            @flavor.Name
          </li>
        }
      </ul>
    }

    <div class="text-center">
      <input type="submit" value="Save" class="btn btn-primary btn-lg" />
    </div>
  }
</div>

PierresTreats/Views/Treats/Create.cshtml
@{
  Layout = "_Layout";
}

@using PierresTreats.Models
@model PierresTreats.Models.Treat

<h1>Add New Treat</h1>

<div class="container page-content">
  @using (Html.BeginForm())
  {
    <div class="form-group form-inline">
      @Html.LabelFor(model => model.Name, new{@class = "col-sm-4 col-form-label"})
      @Html.TextBoxFor(model => model.Name, new {@class = "form-control", required="required"})
    </div>
    <div class="form-group form-inline">
      @Html.LabelFor(model => model.Description, new{@class = "col-sm-4 col-form-label"})
      @Html.TextBoxFor(model => model.Description, new {@class = "form-control", required="required"})
    </div>
    <div class="form-group form-inline">
      @Html.LabelFor(model => model.Price, new{@class = "col-sm-4 col-form-label"})
      @Html.TextBoxFor(model => model.Price, new {@class = "form-control", required="required"})
    </div>

    <div>
      <p>Flavor Profile:</p>
      @if (@ViewBag.Flavors.Count == 0)
      {
        <p>No Flavors Selections Added</p>
      }
      else
      {
        <ul>
          @foreach (Flavor flavor in ViewBag.Flavors)
          {
            <li>
              <input type="checkbox" name="flavorIds" value="@flavor.FlavorId" />
              @flavor.Name
            </li>
          }
        </ul>
      }
    </div>

    <div class="text-center my-3">
      <input type="submit" value="Add" class="btn btn-primary btn-lg" />
    </div>
  }
</div>

PierresTreats/Views/Treats/Delete.cshtml
@{
  Layout = "_Layout";
}

<h1>Are you sure you want to delete @Model.Name?</h1>

@using (Html.BeginForm())
{
  <div class="text-center m-5">
    <input type="submit" value="Delete Treat" class="btn btn-danger btn-lg my-2" />
  </div>
}

PierresTreats/Views/Treats/Details.cshtml
@{
  Layout = "_Layout";
}

@using PierresTreats.Models
@model PierresTreats.Models.Treat

<h1>@Html.DisplayFor(model => model.Name)</h1>
<h2 class="additional-info">@Html.DisplayFor(model => model.Description)</h2>

<div class="container page-content">
  <p>@Html.DisplayNameFor(model => model.Price): $@Html.DisplayFor(model => model.Price)</p>

  <p>Great selection if you're in the mood for:</p>
  @if (@Model.FlavorTreatJoinEntities.Count == 0)
  {
    <h5>No Flavors Added</h5>
  }
  else
  {
    <ul>
    @foreach (FlavorTreat join in Model.FlavorTreatJoinEntities)
      {
        <li>
          @using (Html.BeginForm("RemoveFlavor", "Treats"))
          {
            @Html.ActionLink($"{join.Flavor.Name}", "Details", "Flavors", new { id = join.Flavor.FlavorId })
            @Html.Hidden("joinId", @join.FlavorTreatId)
            <button type="submit" class="fas fa-trash-alt btn" title="Remove Flavor"></button>
          }
        </li>
      }
    </ul>
  }
</div>

<div class="text-center m-5">
  @Html.ActionLink("Add Flavor", "AddFlavor", new { id = Model.TreatId }, new { @class = "btn btn-secondary btn-lg mx-2 my-1" })
  @Html.ActionLink("Edit Treat", "Edit", new { id = Model.TreatId }, new { @class = "btn btn-secondary btn-lg mx-2 my-1" })
  @Html.ActionLink("Delete Treat", "Delete", new { id = Model.TreatId }, new { @class = "btn btn-secondary btn-lg mx-2 my-1" })
</div>

PierresTreats/Views/Treats/Edit.cshtml
@{
  Layout = "_Layout";
}


@using PierresTreats.Models
@model PierresTreats.Models.Treat

<h1>Add New Treat</h1>

<div class="container page-content">
  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.TreatId)
    <div class="form-group form-inline">
      @Html.LabelFor(model => model.Name, new{@class = "col-sm-4 col-form-label"})
      @Html.TextBoxFor(model => model.Name, new {@class = "form-control", required="required"})
    </div>
    <div class="form-group form-inline">
      @Html.LabelFor(model => model.Description, new{@class = "col-sm-4 col-form-label"})
      @Html.TextBoxFor(model => model.Description, new {@class = "form-control", required="required"})
    </div>
    <div class="form-group form-inline">
      @Html.LabelFor(model => model.Price, new{@class = "col-sm-4 col-form-label"})
      @Html.EditorFor(model => model.Price, new {@class = "form-control", required="required"})
    </div>

    <div class="text-center my-3">
      <input type="submit" value="Save" class="btn btn-primary btn-lg" />
    </div>
  }
</div>

PierresTreats/Views/Treats/Index.cshtml
@{
  Layout = "_Layout";
}

@using PierresTreats.Models;

<h1>Treats</h1>

<div class="container page-content py-4">
  @if (@Model.Count == 0)
  {
    <h3>No treats have been added!</h3>
  }
  else
  {
    <ul>
      @foreach (Treat treat in Model)
      {
        <li>@Html.ActionLink($"{treat.Name}", "Details", new { id = treat.TreatId })</li>
      }
    </ul>
  }
</div>