PierresTreats/Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PierresTreats.Models
{
  public class Order
  {
    public int OrderId { get; set; }

    [Display(Name = "Ordered Date")]
    [DataType(DataType.Date)]
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
    public DateTime OrderDate { get; set; }

    [Display(Name = "Requested Delivery Date")]
    [DataType(DataType.Date)]
    [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
    public DateTime DeliveryDate { get; set; }

    public virtual ICollection<OrderTreat> OrderTreatJoinEntities { get; }
    public virtual ApplicationUser User { get; set; }

    public Order()
    {
      this.OrderTreatJoinEntities = new HashSet<OrderTreat>();
      this.OrderDate = DateTime.Now;
    }

    public decimal GetOrderTotal()
    {
      decimal orderTotal = 0;
      foreach (OrderTreat entry in this.OrderTreatJoinEntities)
      {
        decimal lineItemPrice = (decimal)entry.TreatQuantity * entry.Treat.Price;
        orderTotal += lineItemPrice;
      }
      return orderTotal;
    }
  }
}

PierresTreats/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PierresTreats.Models;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace PierresTreats.Controllers
{
  [Authorize]
  public class OrdersController : Controller
  {
    private readonly PierresTreatsContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public OrdersController(PierresTreatsContext db, UserManager<ApplicationUser> userManager)
    {
      _db = db;
      _userManager = userManager;
    }

    public async Task<ActionResult> Index()
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      List<Order> allUserOrders = _db.Orders.Where(entry => entry.User.Id == currentUser.Id).ToList();
      return View(allUserOrders);
    }

    public ActionResult Create()
    {
      ViewBag.Treats = _db.Treats.ToList();
      return View();
    }

    [HttpPost]
    public async Task<ActionResult> Create(Order order, int[] treatIds, int[] treatQuantities)
    {
      var userId = this.User.FindFirst(ClaimTypes.NameIdentifier)?.Value;
      var currentUser = await _userManager.FindByIdAsync(userId);
      order.User = currentUser;
      _db.Orders.Add(order);
      _db.SaveChanges();
      for (int i = 0; i < treatIds.Length; i++)
      {
        if (treatQuantities[i] != 0)
        {
          _db.OrderTreat.Add(new OrderTreat()
          { OrderId = order.OrderId, TreatId = treatIds[i], TreatQuantity = treatQuantities[i] });
        }
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Details(int id)
    {
      Order selectedOrder = _db.Orders
        .Include(order => order.OrderTreatJoinEntities)
        .ThenInclude(join => join.Treat)
        .FirstOrDefault(order => order.OrderId == id);
      return View(selectedOrder);
    }

    public ActionResult Edit(int id)
    {
      Order selectedOrder = _db.Orders.FirstOrDefault(order => order.OrderId == id);
      return View(selectedOrder);
    }

    [HttpPost]
    public ActionResult Edit(Order order)
    {
      _db.Entry(order).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = order.OrderId });
    }

    public ActionResult Delete(int id)
    {
      Order selectedOrder = _db.Orders.FirstOrDefault(order => order.OrderId == id);
      return View(selectedOrder);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Order selectedOrder = _db.Orders.FirstOrDefault(order => order.OrderId == id);
      _db.Orders.Remove(selectedOrder);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddTreat(int id)
    {
      Order selectedOrder = _db.Orders.FirstOrDefault(order => order.OrderId == id);
      ViewBag.Treats = _db.Treats.ToList();
      return View(selectedOrder);
    }

    [HttpPost]
    public ActionResult AddTreat(Order order, int[] treatIds, int[] treatQuantities)
    {
      for (int i = 0; i < treatIds.Length; i++)
      {
        if (treatQuantities[i] != 0)
        {
          bool entryExists = _db.OrderTreat
            .Any(entry => entry.OrderId == order.OrderId && entry.TreatId == treatIds[i]);
          if (!entryExists)
          {
            _db.OrderTreat.Add(new OrderTreat() { OrderId = order.OrderId, TreatId = treatIds[i], TreatQuantity = treatQuantities[i] });
          }
          else
          {
            OrderTreat joinEntry = _db.OrderTreat.FirstOrDefault(entry => entry.OrderId == order.OrderId && entry.TreatId == treatIds[i]);
            joinEntry.TreatQuantity += treatQuantities[i];
            _db.Entry(order).State = EntityState.Modified;

          }
        }
      }
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = order.OrderId });
    }

    [HttpPost]
    public ActionResult RemoveTreat(int joinId)
    {
      OrderTreat joinEntry = _db.OrderTreat.FirstOrDefault(entry => entry.OrderTreatId == joinId);
      int orderId = joinEntry.OrderId;
      _db.OrderTreat.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = orderId });
    }
  }
}

PierresTreats/Controllers/TreatsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PierresTreats.Models;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace PierresTreats.Controllers
{
  [Authorize]
  public class TreatsController : Controller
  {
    private readonly PierresTreatsContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public TreatsController(PierresTreatsContext db, UserManager<ApplicationUser> userManager)
    {
      _db = db;
      _userManager = userManager;
    }

    [AllowAnonymous]
    public ActionResult Index()
    {
      List<Treat> allTreats = _db.Treats.ToList();
      return View(allTreats);
    }

    public ActionResult Create()
    {
      ViewBag.Flavors = _db.Flavors.ToList();
      return View();
    }

    [HttpPost]
    public ActionResult Create(Treat treat, int[] flavorIds)
    {
      _db.Treats.Add(treat);
      _db.SaveChanges();
      foreach (int flavorId in flavorIds)
      {
        bool entryExists = _db.FlavorTreat
          .Any(entry => entry.FlavorId == flavorId && entry.TreatId == treat.TreatId);
        if (!entryExists)
        {
          _db.FlavorTreat.Add(new FlavorTreat() { FlavorId = flavorId, TreatId = treat.TreatId });
        }
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [AllowAnonymous]
    public ActionResult Details(int id)
    {
      Treat selectedTreat = _db.Treats
        .Include(treat => treat.FlavorTreatJoinEntities)
        .ThenInclude(join => join.Flavor)
        .FirstOrDefault(treat => treat.TreatId == id);
      return View(selectedTreat);
    }

    public ActionResult Edit(int id)
    {
      Treat selectedTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(selectedTreat);
    }

    [HttpPost]
    public ActionResult Edit(Treat treat)
    {
      _db.Entry(treat).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = treat.TreatId });
    }

    public ActionResult Delete(int id)
    {
      Treat selectedTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(selectedTreat);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Treat selectedTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      _db.Treats.Remove(selectedTreat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddFlavor(int id)
    {
      Treat selectedTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      ViewBag.Flavors = _db.Flavors.ToList();
      return View(selectedTreat);
    }

    [HttpPost]
    public ActionResult AddFlavor(Treat treat, int[] flavorIds)
    {
      foreach (int flavorId in flavorIds)
      {
        bool entryExists = _db.FlavorTreat
          .Any(entry => entry.FlavorId == flavorId && entry.TreatId == treat.TreatId);
        if (!entryExists)
        {
          _db.FlavorTreat.Add(new FlavorTreat() { FlavorId = flavorId, TreatId = treat.TreatId });
        }
      }
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = treat.TreatId });
    }

    [HttpPost]
    public ActionResult RemoveFlavor(int joinId)
    {
      FlavorTreat joinEntry = _db.FlavorTreat.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
      int treatId = joinEntry.TreatId;
      _db.FlavorTreat.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = treatId });
    }
  }
}

PierresTreats/Views/Orders/AddTreat.cshtml
@{
  Layout = "_Layout";
}

@using PierresTreats.Models
@model PierresTreats.Models.Order

<h1>Add Treats to Order #@Html.DisplayFor(model => model.OrderId)</h1>

<div class="container page-content">
  <h4>Treat Options:</h4>
  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.OrderId)

    @if (@ViewBag.Treats.Count == 0)
    {
      <p>No Treat Selections Added</p>
    }
    else
    {
      <ul>
        @foreach (Treat treat in ViewBag.Treats)
        {
          <li>
            @Html.Hidden("treatIds", @treat.TreatId)
            <div class="row mx-3 my-1">
              @Html.TextBox("treatQuantities", 0, new { @class="form-control quantity-input mx-3", type="number" })
              @String.Format("{0} - {1:C}", treat.Name, treat.Price)
            </div>
          </li>
        }
      </ul>
    }

    <div class="text-center">
      <input type="submit" value="Add to Order" class="btn btn-primary btn-lg" />
    </div>
  }
</div>

PierresTreats/Views/Orders/Create.cshtml
@{
  Layout = "_Layout";
}

@using PierresTreats.Models
@model PierresTreats.Models.Order

<h1>Start New Order</h1>

<div class="container page-content">
  @using (Html.BeginForm())
  {
    <div class="form-group form-inline">
      @Html.LabelFor(model => model.DeliveryDate, new{@class = "col-sm-5 col-form-label"})
      @Html.TextBoxFor(model => model.DeliveryDate, new {@class = "form-control", required="required", type="date"})
    </div>

    <div>
      <p>Treat Options:</p>
      @if (@ViewBag.Treats.Count == 0)
      {
        <p>No Treat Selections Added</p>
      }
      else
      {
        <ul>
          @foreach (Treat treat in ViewBag.Treats)
          {
            <li>
              @Html.Hidden("treatIds", @treat.TreatId)
              <div class="row mx-3 my-1">
                @Html.TextBox("treatQuantities", 0, new { @class="form-control quantity-input mx-3", type="number" })
                @String.Format("{0} - {1:C}", treat.Name, treat.Price)
              </div>
            </li>
          }
        </ul>
      }
    </div>

    <div class="text-center my-3">
      <input type="submit" value="Add" class="btn btn-primary btn-lg" />
    </div>
  }
</div>

PierresTreats/Views/Orders/Delete.cshtml
@{
  Layout = "_Layout";
}

<h1>Are you sure you want to cancel Order #@Model.OrderId?</h1>

@using (Html.BeginForm())
{
  <div class="text-center m-5">
    <input type="submit" value="Cancel Order" class="btn btn-danger btn-lg my-2" />
  </div>
}

PierresTreats/Views/Orders/Details.cshtml
@{
  Layout = "_Layout";
}

@using PierresTreats.Models
@model PierresTreats.Models.Order

<h1>Order #@Html.DisplayFor(model => model.OrderId)</h1>

<div class="container page-content">
  <h2>@Html.DisplayNameFor(model => model.DeliveryDate): @Html.DisplayFor(model => model.DeliveryDate)</h2>

  @if (@Model.OrderTreatJoinEntities.Count == 0)
  {
    <h5>No Treats Added</h5>
  }
  else
  {
    <ul>
    @foreach (OrderTreat join in Model.OrderTreatJoinEntities)
      {
        <li>
          @using (Html.BeginForm("RemoveTreat", "Orders"))
          {
            @Html.ActionLink($"{join.Treat.Name}", "Details", "Treats", new { id = join.Treat.TreatId })
            @String.Format(" x{0} - {1:C}", join.TreatQuantity, join.Treat.Price * join.TreatQuantity)
            @Html.Hidden("joinId", @join.OrderTreatId)
            <button type="submit" class="fas fa-trash-alt btn" title="Remove Treat"></button>
          }
        </li>
      }
    </ul>

    <p>@String.Format("Total: {0:C}", Model.GetOrderTotal())</p>
  }
</div>

<div class="text-center m-5">
  @Html.ActionLink("Add Treat", "AddTreat", new { id = Model.OrderId }, new { @class = "btn btn-secondary btn-lg mx-2 my-1" })
  @Html.ActionLink("Edit Order", "Edit", new { id = Model.OrderId }, new { @class = "btn btn-secondary btn-lg mx-2 my-1" })
  @Html.ActionLink("Cancel Order", "Delete", new { id = Model.OrderId }, new { @class = "btn btn-secondary btn-lg mx-2 my-1" })
</div>

PierresTreats/Views/Orders/Edit.cshtml
@{
  Layout = "_Layout";
}


@using PierresTreats.Models
@model PierresTreats.Models.Order

<h1>Edit Order #@Html.DisplayFor(model => model.OrderId)</h1>

<div class="container page-content">
  @using (Html.BeginForm())
  {
    @Html.HiddenFor(model => model.OrderId)
    <div class="form-group form-inline">
      @Html.LabelFor(model => model.DeliveryDate, new{@class = "col-sm-5 col-form-label"})
      @Html.TextBoxFor(model => model.DeliveryDate, new {@class = "form-control", required="required", type="date"})
    </div>

    <div class="text-center my-3">
      <input type="submit" value="Save" class="btn btn-primary btn-lg" />
    </div>
  }
</div>

PierresTreats/Views/Orders/Index.cshtml
@{
  Layout = "_Layout";
}

@using PierresTreats.Models;

<h1>Orders</h1>

<div class="container page-content py-4">
  @if (@Model.Count == 0)
  {
    <h3>No orders have been added!</h3>
  }
  else
  {
    <ul>
      @foreach (Order order in Model)
      {
        <li>@Html.ActionLink($"Order #{order.OrderId}", "Details", new { id = order.OrderId }) for @order.DeliveryDate.Date.ToString("d")</li>
      }
    </ul>
  }
</div>

<div class="text-center m-5">
  @Html.ActionLink("New Order", "Create", "Orders", null, new { @class = "btn btn-secondary btn-lg mx-2 my-1" })
</div>